pub mod ansi;
pub mod buffer;
pub mod buffer_manager;
pub mod chat_renderer;
pub mod input;
pub mod input_handler;
pub mod input_history;
pub mod input_line_state;
pub mod layout;
pub mod message_buffer;
pub mod mirc_colors;
pub mod renderer;
pub mod scrollback_search;
pub mod signal;
pub mod status_bar;
pub mod style;
pub mod tab_bar;
pub mod tab_completion;
mod terminal;
pub mod view_coordinator;

pub use buffer_manager::{BufferId, BufferManager};
pub use chat_renderer::{nick_color, render_chat_area};
pub use input::{InputReader, KeyEvent};
pub use input_handler::{InputAction, InputHandler};
pub use input_history::InputHistory;
pub use input_line_state::InputLineState;
pub use layout::{Layout, Rect};
pub use message_buffer::{BufferLine, LineType, MessageBuffer};
pub use scrollback_search::{render_search_bar, SearchDirection, SearchState};
pub use signal::SignalHandler;
pub use status_bar::{render_status_bar, StatusBarInfo};
pub use tab_bar::{render_tab_bar, TabInfo};
pub use tab_completion::TabCompleter;
pub use terminal::{terminal_size, RawModeGuard, TerminalSize};
pub use view_coordinator::{ViewAction, ViewCoordinator};
